// <auto-generated />
using System;
using FinancialCrm.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancialCrm.DataAccess.Migrations
{
    [DbContext(typeof(FinancialCrmContext))]
    [Migration("20260129152636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancialCrm.DataAccess.Entities.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankId"));

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BankBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("BankTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BankId");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("FinancialCrm.DataAccess.Entities.BankProcess", b =>
                {
                    b.Property<int>("BankProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BankProcessId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessType")
                        .HasColumnType("integer");

                    b.HasKey("BankProcessId");

                    b.HasIndex("BankId");

                    b.ToTable("BankProcesses");
                });

            modelBuilder.Entity("FinancialCrm.DataAccess.Entities.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillId"));

                    b.Property<decimal>("BillAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("BillPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.HasKey("BillId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("FinancialCrm.DataAccess.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FinancialCrm.DataAccess.Entities.Spending", b =>
                {
                    b.Property<int>("SpendingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpendingId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SpendingAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SpendingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpendingTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpendingId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Spendings");
                });

            modelBuilder.Entity("FinancialCrm.DataAccess.Entities.BankProcess", b =>
                {
                    b.HasOne("FinancialCrm.DataAccess.Entities.Bank", "Bank")
                        .WithMany("BankProcesses")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("FinancialCrm.DataAccess.Entities.Spending", b =>
                {
                    b.HasOne("FinancialCrm.DataAccess.Entities.Category", "Category")
                        .WithMany("Spendings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinancialCrm.DataAccess.Entities.Bank", b =>
                {
                    b.Navigation("BankProcesses");
                });

            modelBuilder.Entity("FinancialCrm.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Spendings");
                });
#pragma warning restore 612, 618
        }
    }
}
